spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: EDU_TRACK
    password: edu1234

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.edutrack.model
    configuration:
      map-underscore-to-camel-case: true

server:
  port: 8090